export const CONVERSION_RATE = 1000; // 1000 naira = 100 points
export const POINTS_PER_NAIRA = CONVERSION_RATE / 1000;

export const RAFFLE_STATUSES = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const TICKET_STATUSES = {
  ACTIVE: 'ACTIVE',
  WON: 'WON',
  LOST: 'LOST',
};

export const TASK_TYPES = {
  WATCH_AD: 'WATCH_AD',
  REFERRAL: 'REFERRAL',
  SOCIAL_SHARE: 'SOCIAL_SHARE',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  DAILY_LOGIN: 'DAILY_LOGIN',
  INVITE_FRIEND: 'INVITE_FRIEND',
};
