#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running pre-commit code checks..."

# Check Biome / Lint formatting
if command -v biome >/dev/null 2>&1; then
  biome check . || exit 1
fi

echo "✅ Pre-commit checks passed!"
